# Generated by Django 5.2.4 on 2025-09-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unique_id',
            field=models.CharField(default='default123', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
